# Open-Sankoré Community Edition
#
# Copyright (C) 2026 David Guyomarch
#
# SPDX-License-Identifier: GPL-3.0-only

  TARGET = OpenSankoreTests
TEMPLATE = app

CONFIG += testcase console c++20
CONFIG -= app_bundle

QT += core gui widgets testlib xml network svg svgwidgets

# Paths — tests/ shims take priority over ../src for stubbed headers
INCLUDEPATH += .
INCLUDEPATH += stubs
INCLUDEPATH += ../src

# We only compile the utility sources under test (no app dependencies)
# This avoids pulling in UBApplication, UBPersistenceManager, etc.

# Headers under test
HEADERS += ../src/frameworks/UBStringUtils.h \
           ../src/frameworks/UBGeometryUtils.h \
           ../src/frameworks/UBVersion.h \
           ../src/frameworks/UBBase32.h \
           ../src/core/UB.h \
           ../src/web/UBOEmbedUtils.h \
           ../src/adaptors/UBSvgTransformUtils.h \
           ../src/adaptors/UBMetadataLoader.h \
           ../src/domain/UBSceneContext.h \
           ../src/domain/UBItem.h \
           ../src/domain/UBSmoothStrokeItem.h \
           tst_UBGraphicsScene.h \
           tst_UBVisualRegression.h \
           tst_UBRecognition.h \
           tst_UBSmoothStrokeItem.h

# Sources under test (only self-contained utilities)
SOURCES += ../src/frameworks/UBStringUtils.cpp \
           ../src/frameworks/UBGeometryUtils.cpp \
           ../src/frameworks/UBVersion.cpp \
           ../src/frameworks/UBBase32.cpp \
           ../src/adaptors/UBIniFileParser.cpp \
           ../src/adaptors/UBSvgTransformUtils.cpp \
           ../src/core/UBForeignObjectsUtils.cpp

# For UBFileSystemUtils we need a minimal version without OpenSSL/QuaZip deps
# We provide a test stub instead (not in HEADERS to avoid moc issues on Linux)
# Real source instead of stub (no QuaZip dependency)
SOURCES += ../src/frameworks/UBFileSystemUtilsCore.cpp
SOURCES += ../src/domain/UBSceneContext.cpp

# UBFileSystemUtils moc handling
# On Linux, moc cannot parse UBFileSystemUtils.h (GCC 11 type_traits error via moc_predefs.h)
# Solution: on Windows moc works fine (header in HEADERS); on Linux the CI pre-generates
# the moc output without moc_predefs.h into premoc/ before make runs
win32-msvc* {
    HEADERS += ../src/frameworks/UBFileSystemUtils.h
} else {
    # moc output is pre-generated by CI before make runs (see build-linux.yml)
    SOURCES += premoc/moc_UBFileSystemUtils.cpp
}

# UBCryptoUtils stub (bypasses UBApplication singleton)
# Not in HEADERS to avoid moc parsing system headers on Linux
SOURCES += stubs/UBCryptoUtils_stub.cpp

# UBOEmbedParser — tests compile the real UBOEmbedUtils.cpp (parsing logic)
# and the real UBOEmbedParser.cpp (QObject) for the #229 regression tests.
SOURCES += ../src/web/UBOEmbedUtils.cpp
SOURCES += ../src/web/UBOEmbedParser.cpp

# UBOEmbedParser is a QObject: moc is pre-generated to avoid the Linux moc bug
# (see build/moc handling below and docker-build.sh).
win32-msvc* {
    HEADERS += ../src/web/UBOEmbedParser.h
} else {
    SOURCES += premoc/moc_UBOEmbedParser.cpp
}

# UBMetadataDcSubsetAdaptor — tests compile the real UBMetadataLoader.cpp (load logic)
SOURCES += ../src/adaptors/UBMetadataLoader.cpp

# UBDocumentProxy — compile real source with header shims for deps
# To regenerate moc: moc -I. -I../src ../src/document/UBDocumentProxy.h -o premoc/moc_UBDocumentProxy.cpp
SOURCES += stubs/UBSettings_stub.cpp \
           stubs/UBDocumentManager_stub.cpp \
           ../src/document/UBDocumentProxy.cpp \
           premoc/moc_UBSettings_stub.cpp \
           premoc/moc_UBDocumentManager_stub.cpp \
           premoc/moc_UBDocumentProxy_stub.cpp

# UBPlatformUtils stub
SOURCES += stubs/UBPlatformUtils_stub.cpp

# Test headers — simple ones that moc can handle directly
# NOTE: moved to premoc/ due to moc bug on Linux CI (cannot parse system C++ headers)

# Test headers — not in HEADERS (premoc used instead to avoid moc issues on Linux)

# UBBoardSubControllers — stub with static methods only (no app deps)

# Test sources
SOURCES += main.cpp \
           tst_UBStringUtils.cpp \
           tst_UBFileSystemUtils.cpp \
           tst_UBGeometryUtils.cpp \
           tst_UBCryptoUtils.cpp \
           tst_UBDocumentProxy.cpp \
           tst_UBSettings.cpp \
           tst_UBVersion.cpp \
           tst_UBBase32.cpp \
           tst_UBIniFileParser.cpp \
           tst_UBMetadataDcSubsetAdaptor.cpp \
           tst_UBOEmbedParser.cpp \
           tst_UBSvgTransform.cpp \
           tst_UBForeignObjectsHelper.cpp \
           tst_UBGraphicsScene.cpp \
           tst_UBVisualRegression.cpp \
           tst_UBRecognition.cpp \
           tst_UBSmoothStrokeItem.cpp \
           stubs/UBSmoothStrokeItem_testable.cpp \
           premoc/moc_tst_UBStringUtils.cpp \
           premoc/moc_tst_UBFileSystemUtils.cpp \
           premoc/moc_tst_UBGeometryUtils.cpp \
           premoc/moc_tst_UBCryptoUtils.cpp \
           premoc/moc_tst_UBDocumentProxy.cpp \
           premoc/moc_tst_UBSettings.cpp \
           premoc/moc_tst_UBVersion.cpp \
           premoc/moc_tst_UBBase32.cpp \
           premoc/moc_tst_UBIniFileParser.cpp \
           premoc/moc_tst_UBMetadataDcSubsetAdaptor.cpp \
           premoc/moc_tst_UBOEmbedParser.cpp \
           premoc/moc_tst_UBSvgTransform.cpp \
           premoc/moc_tst_UBForeignObjectsHelper.cpp


# Build output
DESTDIR = build
OBJECTS_DIR = build/objects
MOC_DIR = build/moc

# Resources for visual regression tests
RESOURCES += visual_tests.qrc

# OpenSSL for UBCryptoUtils
win32-msvc* {
    # Static linking to avoid DLL loading issues on CI
    OPENSSL_STATIC_PATH = $$(VCPKG_ROOT)/installed/x64-windows-static
    !isEmpty(OPENSSL_STATIC_PATH):exists($$OPENSSL_STATIC_PATH/lib/libcrypto.lib) {
        INCLUDEPATH += $$OPENSSL_STATIC_PATH/include
        LIBS += -L$$OPENSSL_STATIC_PATH/lib -llibcrypto
        LIBS += -lws2_32 -lcrypt32 -ladvapi32 -luser32
    } else {
        # Fallback to dynamic
        VCPKG_ROOT_PATH = $$(VCPKG_ROOT)
        INCLUDEPATH += $$VCPKG_ROOT_PATH/installed/x64-windows/include
        LIBS += -L$$VCPKG_ROOT_PATH/installed/x64-windows/lib -llibcrypto
    }
} else {
    LIBS += -lcrypto
}

# Code coverage (GCC/Clang only — not available on MSVC)
!win32-msvc* {
    QMAKE_CXXFLAGS += --coverage
    QMAKE_LFLAGS += --coverage
}
