/*
 * PLACEHOLDER: This file is regenerated by CI before compilation.
 * 
 * On Linux, Qt's moc cannot parse UBFileSystemUtils.h because the
 * --include moc_predefs.h mechanism pulls GCC 11's <type_traits>
 * which causes a "Parse error at std" failure.
 *
 * The CI workflow (build-linux.yml) regenerates this file by running moc
 * WITHOUT moc_predefs.h. On Windows/MSVC this problem does not occur,
 * so the header is listed directly in HEADERS.
 *
 * If building locally on Linux, run:
 *   cd tests
 *   $(QTDIR)/libexec/moc -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB \
 *     -I$(QTDIR)/include -I$(QTDIR)/include/QtCore \
 *     -I$(QTDIR)/include/QtGui -I$(QTDIR)/include/QtWidgets \
 *     -I. -I../src ../src/frameworks/UBFileSystemUtils.h -o premoc/moc_UBFileSystemUtils.cpp
 */
#error "This placeholder must be regenerated by CI or manually (see comment above)"
