/*
 * Copyright (C) 2010-2013 Groupement d'Intérêt Public pour l'Education Numérique en Afrique (GIP ENA)
 * Copyright (C) 2026 David Guyomarch
 *
 * This file is part of Open-Sankoré.
 *
 * Open-Sankoré is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3 of the License,
 * with a specific linking exception for the OpenSSL project's
 * "OpenSSL" library (or with modified versions of it that use the
 * same license as the "OpenSSL" library).
 *
 * Open-Sankoré is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Open-Sankoré.  If not, see <http://www.gnu.org/licenses/>.
 */



#include "UBApplication.h"

#include <QTimer>

// Git version (generated by CI: tag or commit hash)
#if __has_include("git_version.h")
#include "git_version.h"
#endif
#ifndef GIT_VERSION
#define GIT_VERSION ""
#endif

#include <QWidget>
#include <QApplication>
#include <QGuiApplication>
#include <QScreen>
#include <QPainter>
#include <QFile>

#ifdef SANKORE_WEBENGINE
#include <QWebEngineView>
#include <QWebEngineProfile>
#include <QWebEngineSettings>
#endif
#include <QDesktopServices>
#include <QMenu>
#include <QActionGroup>
#include <QDir>
#include <QDomDocument>
#include <QDomElement>
#include <QFile>
#include <QIODevice>
#include <QList>
#include <QLocale>
#include <QMap>
#include <QObject>
#include <QPixmapCache>
#include <QRect>
#include <QRegularExpression>
#include <QSize>
#include <QString>
#include <QStringList>
#include <QTimer>
#include <QTranslator>
#include <QVariant>
#include <QFontDatabase>

#if defined(Q_OS_MACOSX)
#include <Carbon/Carbon.h>
#endif

#include "frameworks/UBPlatformUtils.h"
#include "frameworks/UBFileSystemUtils.h"
#include "frameworks/UBStringUtils.h"

#include "UBSettings.h"
#include "UBTheme.h"
#include "qml/UBThemeManager.h"
#include "recognition/UBRecognitionController.h"
#include "UBSetting.h"
#include "UBPersistenceManager.h"
#include "UBDocumentManager.h"
#include "UBPreferencesController.h"
#include "UBIdleTimer.h"
#include "UBApplicationController.h"

#include "board/UBBoardController.h"
#include "board/UBDrawingController.h"
#include "board/UBBoardView.h"
#include "board/UBBoardPaletteManager.h"
#include "controllers/UBToolController.h"
#include "web/UBWebController.h"

#include "document/UBDocumentController.h"
#include "document/UBDocumentProxy.h"

#include "gui/UBMainWindow.h"
#include "gui/UBResources.h"

#include "adaptors/publishing/UBSvgSubsetRasterizer.h"

#include "ui_mainWindow.h"

#include "frameworks/UBCryptoUtils.h"
#include "tools/UBToolsManager.h"

#include "UBDisplayManager.h"

QPointer<QUndoStack> UBApplication::undoStack;

UBApplicationController* UBApplication::applicationController = 0;
UBBoardController* UBApplication::boardController = 0;
UBWebController* UBApplication::webController = 0;
UBDocumentController* UBApplication::documentController = 0;
UBMainWindow* UBApplication::mainWindow = 0;

const QString UBApplication::mimeTypeUniboardDocument = QString("application/vnd.mnemis-uniboard-document");
const QString UBApplication::mimeTypeUniboardPage = QString("application/vnd.mnemis-uniboard-page");
const QString UBApplication::mimeTypeUniboardPageItem =  QString("application/vnd.mnemis-uniboard-page-item");
const QString UBApplication::mimeTypeUniboardPageThumbnail = QString("application/vnd.mnemis-uniboard-thumbnail");

#ifdef Q_OS_MACOS
bool bIsMinimized = false;
#endif

QObject* UBApplication::staticMemoryCleaner = 0;

#if defined(Q_OS_MACOS)
static OSStatus ub_appleEventProcessor(const AppleEvent *ae, AppleEvent *event, long handlerRefCon)
{
    Q_UNUSED(event);
    OSType aeID = typeWildCard;
    OSType aeClass = typeWildCard;

    AEGetAttributePtr(ae, keyEventClassAttr, typeType, 0, &aeClass, sizeof(aeClass), 0);
    AEGetAttributePtr(ae, keyEventIDAttr, typeType, 0, &aeID, sizeof(aeID), 0);

    if (aeClass == kCoreEventClass && aeID == kAEReopenApplication)
    {
        // User clicked on Uniboard in the Dock
        ((UBApplicationController*)handlerRefCon)->hideDesktop();
        return noErr;
    }

    return eventNotHandledErr;
}
#endif


UBApplication::UBApplication(const QString &id, int &argc, char **argv) : QtSingleApplication(id, argc, argv)
  , mPreferencesController(nullptr)
  , mApplicationTranslator(nullptr)
  , mQtGuiTranslator(nullptr)
{
    staticMemoryCleaner = new QObject(0); // deleted in UBApplication destructor

    setOrganizationName("Sankore");
    setOrganizationDomain("sankore.org");
    setApplicationName("Open-Sankore");

    setApplicationVersion(QString(GIT_VERSION).isEmpty() ? UBVERSION : GIT_VERSION);

#if defined(Q_OS_MACOS) && !defined(QT_NO_DEBUG)
    CFStringRef shortVersion = (CFStringRef)CFBundleGetValueForInfoDictionaryKey(CFBundleGetMainBundle(), CFSTR("CFBundleShortVersionString"));
    const char *version = CFStringGetCStringPtr(shortVersion, kCFStringEncodingMacRoman);
    Q_ASSERT(version);
    setApplicationVersion(version);
#endif

    QStringList args = arguments();

    mIsVerbose = args.contains("-v")
        || args.contains("-verbose")
        || args.contains("verbose")
        || args.contains("-log")
        || args.contains("log");


    UBSettings *settings = UBSettings::settings();
    mSettings = settings;

    setupTranslators(args);

    UBResources::resources();

    if (!undoStack)
        undoStack = new QUndoStack(staticMemoryCleaner);

    UBPlatformUtils::init();

    connect(settings->appToolBarPositionedAtTop, &UBSetting::changed, this, &UBApplication::toolBarPositionChanged);
    connect(settings->appToolBarDisplayText, &UBSetting::changed, this, &UBApplication::toolBarDisplayTextChanged);
    updateProtoActionsState();

#ifndef Q_OS_MACOS
    setWindowIcon(QIcon(":/images/icon-proposal-2-board-stylus.svg"));
#endif

    // Load global stylesheet based on saved theme preference
    QString theme = UBSettings::settings()->appTheme->get().toString();
    QString qssResource = ":/themes/" + theme + "/style.qss";
    QFile styleFile(qssResource);
    if (styleFile.open(QIODevice::ReadOnly | QIODevice::Text))
    {
        setStyleSheet(styleFile.readAll());
        styleFile.close();
    }

    // Update palette colors to match the active theme at startup
    if (theme == "classic" || theme == "light")
    {
        UBSettings::paletteColor = QColor(245, 245, 245, 220);
        UBSettings::opaquePaletteColor = QColor(255, 255, 255, 240);
    }

    setStyle(new UBStyle()); // Style is owned and deleted by the application

    // Legacy Uniboard.css — only apply if no theme stylesheet was loaded
    if (styleSheet().isEmpty())
    {
        QString css = UBFileSystemUtils::readTextFile(UBPlatformUtils::applicationResourcesDirectory() + "/etc/Uniboard.css");
        if (css.length() > 0)
            setStyleSheet(css);
    }

    QApplication::setStartDragDistance(8); // default is 4, and is a bit small for tablets

    installEventFilter(this);

}


UBApplication::~UBApplication()
{
    UBPlatformUtils::destroy();

    UBFileSystemUtils::deleteAllTempDirCreatedDuringSession();

    delete mainWindow;
    mainWindow = 0;

    UBPersistenceManager::destroy();

    UBDownloadManager::destroy();

    UBDrawingController::destroy();

    UBSettings::destroy();

    UBCryptoUtils::destroy();

    UBToolsManager::destroy();

    if(mApplicationTranslator != nullptr){
        delete mApplicationTranslator;
        mApplicationTranslator = nullptr;
    }
    if(mQtGuiTranslator!=nullptr){
        delete mQtGuiTranslator;
        mQtGuiTranslator = nullptr;
    }

    delete staticMemoryCleaner;
    staticMemoryCleaner = 0;
}

QString UBApplication::checkLanguageAvailabilityForSankore(QString &language)
{
    QStringList availableTranslations = UBPlatformUtils::availableTranslations();
    if(availableTranslations.contains(language,Qt::CaseInsensitive))
        return language;
    else{
        if(language.length() > 2){
            QString shortLanguageCode = language.left(2);
            if(availableTranslations.contains(shortLanguageCode,Qt::CaseInsensitive))
                return shortLanguageCode;
        }
    }
    return QString("");
}

void UBApplication::setupTranslators(QStringList args)
{
    QString forcedLanguage("");
    if(args.contains("-lang"))
        forcedLanguage=args.at(args.indexOf("-lang") + 1);
    else{
        QString setLanguage = mSettings->appPreferredLanguage->get().toString();
        if(!setLanguage.isEmpty())
            forcedLanguage = setLanguage;
    }

    QString language("");

    if(!forcedLanguage.isEmpty())
        language = checkLanguageAvailabilityForSankore(forcedLanguage);

    if(language.isEmpty()){
        QString systemLanguage = UBPlatformUtils::systemLanguage();
        language = checkLanguageAvailabilityForSankore(systemLanguage);
    }

    if(language.isEmpty()){
        language = "en_US";
        //fallback if no translation are available
    }
    else{
        mApplicationTranslator = new QTranslator(this);
        mQtGuiTranslator = new QTranslator(this);
        mApplicationTranslator->load(UBPlatformUtils::translationPath(QString("sankore_"),language));
        installTranslator(mApplicationTranslator);

        QString qtGuiTranslationPath = UBPlatformUtils::translationPath("qt_", language);


        if(!QFile(qtGuiTranslationPath).exists()){
            qtGuiTranslationPath = UBPlatformUtils::translationPath("qt_", language.left(2));
            if(!QFile(qtGuiTranslationPath).exists())
                qtGuiTranslationPath = "";
        }

        if(!qtGuiTranslationPath.isEmpty()){
            mQtGuiTranslator->load(qtGuiTranslationPath);
            installTranslator(mQtGuiTranslator);
        }
        else
            qDebug() << "Qt gui translation in " << language << " is not available";
    }

    QLocale::setDefault(QLocale(language));
    qDebug() << "Running application in:" << language;
    //Claudio: hack to avoid the lost of translations.
    mSettings->init();
}

int UBApplication::exec(const QString& pFileToImport)
{

    QPixmapCache::setCacheLimit(1024 * 100);

    QString webDbPath = UBSettings::userDataDirectory() + "/web-databases";
    QDir webDbDir(webDbPath);
    if (!webDbDir.exists(webDbPath))
        webDbDir.mkpath(webDbPath);

    // Configure WebEngine default settings
#ifdef SANKORE_WEBENGINE
    QWebEngineSettings *gs = QWebEngineProfile::defaultProfile()->settings();
    gs->setAttribute(QWebEngineSettings::PluginsEnabled, true);
    gs->setAttribute(QWebEngineSettings::LocalStorageEnabled, true);
    gs->setAttribute(QWebEngineSettings::JavascriptCanAccessClipboard, true);
#endif

    mainWindow = new UBMainWindow(0, Qt::FramelessWindowHint);
    mainWindow->setAttribute(Qt::WA_NativeWindow, true);


    mainWindow->actionCopy->setShortcuts(QKeySequence::Copy);
    mainWindow->actionPaste->setShortcuts(QKeySequence::Paste);
    mainWindow->actionCut->setShortcuts(QKeySequence::Cut);


    connect(mainWindow->actionBoard, &QAction::triggered, this, [this]() { showBoard(); });
    connect(mainWindow->actionWeb, &QAction::triggered, this, [this]() { showInternet(); });
    connect(mainWindow->actionDocument, &QAction::triggered, this, [this]() { showDocument(); });
    connect(mainWindow->actionQuit, &QAction::triggered, this, [this]() { closing(); });
    connect(mainWindow, &UBMainWindow::closeEvent_Signal, this, &UBApplication::closeEvent);

    // Sync QML ThemeManager BEFORE creating palettes so QML starts with correct colors
    UBThemeManager::instance()->setCurrentTheme(mSettings->appTheme->get().toString());

    boardController = new UBBoardController(mainWindow);


    boardController->init();


    webController = new UBWebController(mainWindow);


    documentController = new UBDocumentController(mainWindow);


    boardController->paletteManager()->connectToDocumentController();

    UBApplication::mainWindow->actionPen->setChecked(false); // force re-trigger
    UBDrawingController::drawingController()->setStylusTool((int)UBStylusTool::Pen);

    applicationController = new UBApplicationController(boardController->controlView(),
                                                        boardController->displayView(),
                                                        mainWindow,
                                                        staticMemoryCleaner);



    connect(applicationController, &UBApplicationController::mainModeChanged,
            boardController->paletteManager(), &UBBoardPaletteManager::slot_changeMainMode);

    connect(applicationController, &UBApplicationController::desktopMode,
            boardController->paletteManager(), &UBBoardPaletteManager::slot_changeDesktopMode);



    connect(mainWindow->actionDesktop, &QAction::triggered, applicationController, &UBApplicationController::showDesktop);
    connect(mainWindow->actionDesktop, &QAction::triggered, this, [this]() { stopScript(); });
#ifndef Q_OS_MACOS
    connect(mainWindow->actionHideApplication, &QAction::triggered, mainWindow, []() { UBApplication::mainWindow->showMinimized(); });
#else
    connect(mainWindow->actionHideApplication, &QAction::triggered, this, [this]() { showMinimized(); });
#endif

    mPreferencesController = new UBPreferencesController(mainWindow);
    mRecognitionController = new UBRecognitionController(this);

    connect(mainWindow->actionPreferences, &QAction::triggered, mPreferencesController, [this]() { mPreferencesController->show(); });

    toolBarDisplayTextChanged(mSettings->appToolBarDisplayText->get());
    toolBarPositionChanged(mSettings->appToolBarPositionedAtTop->get());

    // Apply theme icons at startup
    reloadThemeIcons(mSettings->appTheme->get().toString());

    // Deferred reload: some palette buttons may not have updated yet
    // (Qt action-observer updates are asynchronous in some cases)
    QString startupTheme = mSettings->appTheme->get().toString();
    QTimer::singleShot(500, this, [this, startupTheme]() {
        reloadThemeIcons(startupTheme);

        // Also refresh dock palette backgrounds (they may have been created
        // before UBSettings::paletteColor was finalized for the active theme)
        if (boardController && boardController->paletteManager())
        {
            // Legacy dock palettes removed — QML V2 uses themeManager
        }
    });

    // Ensure all toolbar actions have tooltips (use text as fallback)
    QList<QToolBar*> toolbars = {mainWindow->boardToolBar, mainWindow->webToolBar, mainWindow->documentToolBar};
    for (QToolBar* toolbar : toolbars)
    {
        for (QAction* action : toolbar->actions())
        {
            if (!action->isSeparator() && action->toolTip().isEmpty())
                action->setToolTip(action->text());
        }
    }

    bool bUseMultiScreen = mSettings->appUseMultiscreen->get().toBool();
    mainWindow->actionMultiScreen->setChecked(bUseMultiScreen);
    connect(mainWindow->actionMultiScreen, &QAction::triggered, applicationController, &UBApplicationController::useMultiScreen);
    connect(mainWindow->actionWidePageSize, &QAction::triggered, boardController, &UBBoardController::setWidePageSize);
    connect(mainWindow->actionWidePageSize_16_10, &QAction::triggered, boardController, &UBBoardController::setWidePageSize16_10);
    connect(mainWindow->actionRegularPageSize, &QAction::triggered, boardController, &UBBoardController::setRegularPageSize);

    connect(mainWindow->actionCut, &QAction::triggered, applicationController, []() { UBApplication::applicationController->actionCut(); });
    connect(mainWindow->actionCopy, &QAction::triggered, applicationController, []() { UBApplication::applicationController->actionCopy(); });
    connect(mainWindow->actionPaste, &QAction::triggered, applicationController, []() { UBApplication::applicationController->actionPaste(); });

    applicationController->initScreenLayout(bUseMultiScreen);
    boardController->setupLayout();

    // Connect OCR zone selection from board view to recognition controller
    connect(boardController->controlView(), &UBBoardView::ocrZoneSelected,
            mRecognitionController, &UBRecognitionController::recognizeZone);

    // Connect Auto-OCR toggle (palette button + menu entry)
    if (mainWindow->actionAutoOcr)
        connect(mainWindow->actionAutoOcr, &QAction::toggled, this, &UBApplication::onAutoOcrToggled);

    // Notify OCR controller when a stroke finishes (mouse release on board)
    connect(boardController->controlView(), &UBBoardView::mouseRelease,
            mRecognitionController, [this]() { mRecognitionController->onStrokeFinished(); });

    if (pFileToImport.length() > 0)
        UBApplication::applicationController->importFile(pFileToImport);

#if defined(Q_OS_MACOS)
    static AEEventHandlerUPP ub_proc_ae_handlerUPP = AEEventHandlerUPP(ub_appleEventProcessor);
    AEInstallEventHandler(kCoreEventClass, kAEReopenApplication, ub_proc_ae_handlerUPP, SRefCon(UBApplication::applicationController), true);
#endif

    // Restored: call showBoard() to properly initialize the board view and palettes
    // In headless/offscreen mode, the window starts tiny (100x30) because there's
    // no window manager. Force a reasonable size BEFORE showBoard() creates palettes.
    if (mainWindow->width() < 800 || mainWindow->height() < 600) {
        QSize fallback(1920, 1080);
        QScreen* screen = QGuiApplication::primaryScreen();
        if (screen && screen->availableSize().width() >= 800)
            fallback = screen->availableSize();
        mainWindow->resize(fallback);
        qDebug() << "Headless mode: forced window resize to" << fallback;
    }
    showBoard();
    mainWindow->showMaximized();

    // Force Pen tool selection after all init is complete (deferred to ensure QML is ready)
    QTimer::singleShot(0, this, [this]() {
        if (boardController && boardController->paletteManager()
            && boardController->paletteManager()->toolController()) {
            auto* tc = boardController->paletteManager()->toolController();
            tc->setActiveTool(UBStylusTool::Pen);
            tc->setPenColorIndex(0); // Black — index 0 in the color palette
        } else {
            UBDrawingController::drawingController()->setStylusTool((int)UBStylusTool::Pen);
        }
    });

    onScreenCountChanged(1);
    return QApplication::exec();
}

void UBApplication::onScreenCountChanged(int newCount)
{
    Q_UNUSED(newCount);
    UBDisplayManager displayManager;
    mainWindow->actionMultiScreen->setEnabled(displayManager.numScreens() > 1);
}

#ifdef Q_OS_MACOS
void UBApplication::showMinimized()
{
    mainWindow->hide();
    bIsMinimized = true;
}

#endif

void UBApplication::startScript()
{
    this->boardController->freezeW3CWidgets(false);
}

void UBApplication::stopScript()
{
    this->boardController->freezeW3CWidgets(true);
}

void UBApplication::showBoard()
{
    applicationController->showBoard();
    boardController->paletteManager()->featuresWidget()->switchToRoot();
}

void UBApplication::showInternet()
{
    applicationController->showInternet();
    webController->showTabAtTop(true);
    boardController->paletteManager()->featuresWidget()->switchToBookmarks();
    stopScript();
}

void UBApplication::showDocument()
{
    applicationController->showDocument();
    startScript();
}

int UBApplication::toolBarHeight()
{
    return mainWindow->boardToolBar->rect().height();
}


void UBApplication::toolBarPositionChanged(QVariant topOrBottom)
{
    Qt::ToolBarArea area;

    if (topOrBottom.toBool())
        area = Qt::TopToolBarArea;
    else
        area = Qt::BottomToolBarArea;

    mainWindow->addToolBar(area, mainWindow->boardToolBar);
    mainWindow->addToolBar(area, mainWindow->webToolBar);
    mainWindow->addToolBar(area, mainWindow->documentToolBar);

    webController->showTabAtTop(topOrBottom.toBool());

}


void UBApplication::toolBarDisplayTextChanged(QVariant display)
{
    Qt::ToolButtonStyle toolButtonStyle = display.toBool() ? Qt::ToolButtonTextUnderIcon : Qt::ToolButtonIconOnly;
    mainWindow->boardToolBar->setToolButtonStyle(toolButtonStyle);
    mainWindow->webToolBar->setToolButtonStyle(toolButtonStyle);
    mainWindow->documentToolBar->setToolButtonStyle(toolButtonStyle);
}

void UBApplication::themeChanged(QAction* action)
{
    if (!action)
        return;

    QString theme = action->data().toString();
    mSettings->appTheme->set(theme);

    // Reload stylesheet from theme directory
    QString qssPath = ":/themes/" + theme + "/style.qss";
    QFile styleFile(qssPath);
    if (styleFile.open(QIODevice::ReadOnly | QIODevice::Text))
    {
        setStyleSheet(styleFile.readAll());
        styleFile.close();
    }

    // Update palette colors based on theme
    if (theme == "classic" || theme == "light")
    {
        UBSettings::paletteColor = QColor(245, 245, 245, 220);
        UBSettings::opaquePaletteColor = QColor(255, 255, 255, 240);
    }
    else
    {
        UBSettings::paletteColor = UBTheme::surface();
        UBSettings::opaquePaletteColor = UBTheme::surfaceOpaque();
    }

    // Sync QML ThemeManager AFTER paletteColor is updated
    // (dock palettes listen to themeChanged and read paletteColor)
    UBThemeManager::instance()->setCurrentTheme(theme);

    // Refresh dock palette backgrounds
    if (boardController && boardController->paletteManager())
    {
        UBBoardPaletteManager* pm = boardController->paletteManager();
        // Legacy dock palettes and stylus/drawing palettes removed — QML V2 uses themeManager
    }

    // Reload toolbar icons from theme directory
    reloadThemeIcons(theme);
}

void UBApplication::reloadThemeIcons(const QString& theme)
{
    QString iconPrefix = ":/themes/" + theme + "/icons/";

    // Static mapping from action objectName to icon filename (from mainWindow.ui)
    static const QMap<QString, QString> actionIconMap = {
        {"actionStylus", "stylus.svg"},
        {"actionBackgrounds", "background.svg"},
        {"actionUndo", "undo.svg"},
        {"actionRedo", "redo.svg"},
        {"actionPages", "newDocument.svg"},
        {"actionBack", "previousPage.svg"},
        {"actionForward", "nextPage.svg"},
        {"actionErase", "clearPage.svg"},
        {"actionGroupItems", "group.svg"},
        {"actionBoard", "board.svg"},
        {"actionWeb", "web.svg"},
        {"actionDocument", "documents.svg"},
        {"actionDesktop", "display.svg"},
        {"actionMenu", "menu.svg"},
        {"actionWebTools", "tools.svg"},
        {"actionWebBack", "previousPage.svg"},
        {"actionWebForward", "nextPage.svg"},
        {"actionWebReload", "reload.svg"},
        {"actionHome", "home.svg"},
        {"actionBookmarks", "bookmarks.svg"},
        {"actionAddBookmark", "addBookmark.svg"},
        {"actionStopLoading", "remove.svg"},
        {"actionDocumentTools", "tools.svg"},
        {"actionNewDocument", "newDocument.svg"},
        {"actionNewFolder", "newFolder.svg"},
        {"actionImport", "import.svg"},
        {"actionExport", "export.svg"},
        {"actionRename", "rename.svg"},
        {"actionOpen", "open.svg"},
        {"actionDuplicate", "duplicate.svg"},
        {"actionDelete", "remove.svg"},
        {"actionCut", "cut.svg"},
        {"actionCopy", "copy.svg"},
        {"actionPaste", "paste.svg"},
        {"actionPreferences", "settings.svg"},
        {"actionMultiScreen", "display.svg"},
        {"actionQuit", "quit.svg"},
        {"actionLibrary", "library.svg"},
        {"actionHideApplication", "hide.svg"},
        {"actionAdd", "addToPage.svg"},
        {"actionDocumentAdd", "addToPage.svg"},
        {"actionAddToWorkingDocument", "addToWorkingDoc.svg"},
        {"actionBookmark", "bookmark.svg"},
        {"actionWebCustomCapture", "captureArea.svg"},
        {"actionWebWindowCapture", "captureWindow.svg"},
        {"actionWebShowHideOnDisplay", "eyeClosed.svg"},
        {"actionWebTrapContent", "addToolToLibrary.svg"},
        {"actionLineSmall", "smallPen.svg"},
        {"actionLineMedium", "mediumPen.svg"},
        {"actionLineLarge", "largePen.svg"},
        {"actionEraserSmall", "smallEraser.svg"},
        {"actionEraserMedium", "mediumEraser.svg"},
        {"actionEraserLarge", "largeEraser.svg"},
        {"actionColor0", "color.svg"},
        {"actionColor1", "color.svg"},
        {"actionColor2", "color.svg"},
        {"actionColor3", "color.svg"},
        {"actionPen", "pen.svg"},
        {"actionEraser", "eraserTool.svg"},
        {"actionMarker", "marker.svg"},
        {"actionSelector", "selector.svg"},
        {"actionHand", "hand.svg"},
        {"actionZoomIn", "zoomIn.svg"},
        {"actionZoomOut", "zoomOut.svg"},
        {"actionPointer", "pointer.svg"},
        {"actionLine", "lineTool.svg"},
        {"actionText", "text.svg"},
        {"actionCapture", "capture.svg"},
        {"actionPlay", "play.svg"},
        {"actionDrawing", "drawing.svg"},
        {"actionVirtualKeyboard", "hand.svg"},
        {"actionOcr", "text.svg"},
    };

    // Reload icons for all toolbar actions
    QList<QToolBar*> toolbars = {mainWindow->boardToolBar, mainWindow->webToolBar, mainWindow->documentToolBar};

    for (QToolBar* toolbar : toolbars)
    {
        for (QAction* action : toolbar->actions())
        {
            if (action->isSeparator() || action->icon().isNull())
                continue;

            QString actionName = action->objectName();
            if (actionIconMap.contains(actionName))
            {
                QString baseName = actionIconMap.value(actionName);
                // Remove extension and try both .svg and .png
                QString stem = baseName.left(baseName.lastIndexOf('.'));
                QString iconPath = iconPrefix + stem + ".svg";
                if (!QFile::exists(iconPath))
                    iconPath = iconPrefix + stem + ".png";
                if (QFile::exists(iconPath))
                    action->setIcon(QIcon(iconPath));
            }
        }
    }

    // Also update actions that are inside widget groups (not directly in toolbar->actions())
    for (auto it = actionIconMap.constBegin(); it != actionIconMap.constEnd(); ++it)
    {
        QAction* action = mainWindow->findChild<QAction*>(it.key());
        if (action)
        {
            QString baseName = it.value();
            QString stem = baseName.left(baseName.lastIndexOf('.'));
            QString iconPath = iconPrefix + stem + ".svg";
            if (!QFile::exists(iconPath))
                iconPath = iconPrefix + stem + ".png";
            if (QFile::exists(iconPath))
                action->setIcon(QIcon(iconPath));
        }
    }
}

void UBApplication::onAutoOcrToggled(bool enabled)
{
    if (mRecognitionController)
        mRecognitionController->setAutoMode(enabled);
    updateAutoOcrIcon(enabled);
}

void UBApplication::updateAutoOcrIcon(bool enabled)
{
    if (!mainWindow || !mainWindow->actionAutoOcr)
        return;

    if (enabled)
        mainWindow->actionAutoOcr->setIcon(QIcon(":/images/stylusPalette/svg/ocr-auto-on.svg"));
    else
        mainWindow->actionAutoOcr->setIcon(QIcon(":/images/stylusPalette/svg/ocr-auto-off.svg"));
}


void UBApplication::closeEvent(QCloseEvent *event)
{
    Q_UNUSED(event);

    closing();
}

void UBApplication::closing()
{
    static bool alreadyClosing = false;
    if (alreadyClosing)
        return;
    alreadyClosing = true;

    if (boardController)
        boardController->closing();

    if (applicationController)
        applicationController->closing();

    if (webController)
        webController->closing();

    mSettings->closing();

    mSettings->appToolBarPositionedAtTop->set(mainWindow->toolBarArea(mainWindow->boardToolBar) == Qt::TopToolBarArea);

    // Defer quit to let any pending menu/widget events finish
    QTimer::singleShot(0, qApp, &QApplication::quit);
}


void UBApplication::showMessage(const QString& message, bool showSpinningWheel)
{
    if (applicationController)
        applicationController->showMessage(message, showSpinningWheel);
}


void UBApplication::setDisabled(bool disable)
{
    boardController->setDisabled(disable);
}


void UBApplication::decorateActionMenu(QAction* action)
{
    for (QWidget* menuWidget : action->associatedWidgets())
    {
        QToolButton *tb = qobject_cast<QToolButton*>(menuWidget);

        if (tb && !tb->menu())
        {
            tb->setObjectName("ubButtonMenu");
            tb->setPopupMode(QToolButton::InstantPopup);
            QMenu* menu = new QMenu(mainWindow);

            QActionGroup* pageSizeGroup = new QActionGroup(mainWindow);
            pageSizeGroup->addAction(mainWindow->actionWidePageSize);
            pageSizeGroup->addAction(mainWindow->actionWidePageSize_16_10);
            pageSizeGroup->addAction(mainWindow->actionRegularPageSize);
            pageSizeGroup->addAction(mainWindow->actionCustomPageSize);

            QMenu* documentSizeMenu = menu->addMenu(QIcon(":/images/toolbar/svg/display.svg"),tr("Page Size"));
            documentSizeMenu->addAction(mainWindow->actionWidePageSize);
            documentSizeMenu->addAction(mainWindow->actionWidePageSize_16_10);
            documentSizeMenu->addAction(mainWindow->actionRegularPageSize);
            documentSizeMenu->addAction(mainWindow->actionCustomPageSize);
            menu->addAction(mainWindow->actionCut);
            menu->addAction(mainWindow->actionCopy);
            menu->addAction(mainWindow->actionPaste);
            menu->addAction(mainWindow->actionHideApplication);
            menu->addAction(mainWindow->actionSleep);

            menu->addSeparator();
            menu->addAction(mainWindow->actionPreferences);

            // Theme sub-menu
            QMenu* themeMenu = menu->addMenu(tr("Theme"));
            QActionGroup* themeGroup = new QActionGroup(themeMenu);
            themeGroup->setExclusive(true);

            QAction* actionThemeDark = themeMenu->addAction(tr("Dark (default)"));
            actionThemeDark->setCheckable(true);
            actionThemeDark->setData("dark");
            themeGroup->addAction(actionThemeDark);

            QAction* actionThemeClassic = themeMenu->addAction(tr("Classic (light)"));
            actionThemeClassic->setCheckable(true);
            actionThemeClassic->setData("classic");
            themeGroup->addAction(actionThemeClassic);

            QAction* actionThemeLight = themeMenu->addAction(tr("Light (modern)"));
            actionThemeLight->setCheckable(true);
            actionThemeLight->setData("light");
            themeGroup->addAction(actionThemeLight);

            QString currentTheme = mSettings->appTheme->get().toString();
            if (currentTheme == "classic")
                actionThemeClassic->setChecked(true);
            else if (currentTheme == "light")
                actionThemeLight->setChecked(true);
            else
                actionThemeDark->setChecked(true);

            connect(themeGroup, &QActionGroup::triggered, this, &UBApplication::themeChanged);

            menu->addAction(mainWindow->actionMultiScreen);

            menu->addSeparator();

            // Auto-OCR also available in menu (mirrors the palette toggle button)
            if (mRecognitionController && mRecognitionController->isAvailable() && mainWindow->actionAutoOcr)
                menu->addAction(mainWindow->actionAutoOcr);

            menu->addSeparator();
            menu->addAction(mainWindow->actionQuit);

            tb->setMenu(menu);
        }
    }
}


void UBApplication::updateProtoActionsState()
{
    if (mainWindow)
    {
        mainWindow->actionMultiScreen->setVisible(true);
    }

    for (QMenu* protoMenu : mProtoMenus)
        protoMenu->setVisible(true);

}


void UBApplication::insertSpaceToToolbarBeforeAction(QToolBar* toolbar, QAction* action, int width)
{
    QWidget* spacer = new QWidget();

    if (width >= 0){
        QHBoxLayout *layout = new QHBoxLayout();
        layout->addSpacing(width);
        spacer->setLayout(layout);
    }
    else
        spacer->setSizePolicy(QSizePolicy::MinimumExpanding, QSizePolicy::Preferred);

    toolbar->insertWidget(action, spacer);
}


bool UBApplication::eventFilter(QObject *obj, QEvent *event)
{
    bool result = QObject::eventFilter(obj, event);

    if (event->type() == QEvent::FileOpen)
    {
        QFileOpenEvent *fileToOpenEvent = static_cast<QFileOpenEvent *>(event);

#if defined(Q_OS_MACOSX)
        ProcessSerialNumber psn;
        GetCurrentProcess(&psn);
        SetFrontProcess(&psn);
#endif

        applicationController->importFile(fileToOpenEvent->file());
    }

    if (event->type() == QEvent::TabletLeaveProximity)
    {
        if (boardController && boardController->controlView())
            boardController->controlView()->forcedTabletRelease();
    }


    if (event->type() == QEvent::ApplicationActivate)
    {
        if (boardController && boardController->controlView())
            boardController->controlView()->setMultiselection(false);
    }

#ifdef Q_OS_MACOS
    if (bIsMinimized && event->type() == QEvent::ApplicationActivate){
        if (mainWindow->isHidden()) mainWindow->show();
        bIsMinimized = false;
    }
#endif
    return result;
}


bool UBApplication::handleOpenMessage(const QString& pMessage)
{
    qDebug() << "received message" << pMessage;

    if (pMessage == UBSettings::appPingMessage)
    {
        qDebug() << "received ping";
        return true;
    }

    qDebug() << "importing file" << pMessage;

    UBApplication::applicationController->importFile(pMessage);

    return true;
}

void UBApplication::cleanup()
{
    if (applicationController) delete applicationController;
    if (boardController) delete boardController;
    if (webController) delete webController;
    if (documentController) delete documentController;

    applicationController = nullptr;
    boardController = nullptr;
    webController = nullptr;
    documentController = nullptr;
}

void UBStyle::drawItemText(QPainter *painter, const QRect &rect, int alignment, const QPalette &pal,
                          bool enabled, const QString& text, QPalette::ColorRole textRole) const
{
    if (text.isEmpty())
        return;

    QPen savedPen;
    if (textRole != QPalette::NoRole)
    {
        savedPen = painter->pen();
        painter->setPen(QPen(pal.brush(textRole), savedPen.widthF()));
    }

    if (!enabled)
    {
        QPen pen = painter->pen();
        QColor half = pen.color();

        half.setRed(half.red() / 2);
        half.setGreen(half.green() / 2);
        half.setBlue(half.blue() / 2);

        painter->setPen(half);
        painter->drawText(rect, alignment, text);
        painter->setPen(pen);
    }

    painter->drawText(rect, alignment, text);

    if (textRole != QPalette::NoRole)
        painter->setPen(savedPen);
}

QString UBApplication::urlFromHtml(QString html)
{
    QString _html;
    QRegularExpression comments("\\<![ \r\n\t]*(--([^\\-]|[\r\n]|-[^\\-])*--[ \r\n\t]*)\\>");
    QString url;
    QDomDocument domDoc;

    //	We remove all the comments & CRLF of this html
    _html = html.remove(comments);
    domDoc.setContent(_html.remove(QRegularExpression("[\\0]")));
    QDomElement rootElem = domDoc.documentElement();

    //  QUICKFIX: Here we have to check rootElem. Sometimes it can be a <meta> tag
    //  In such a case we will not be able to retrieve the src value
    if(rootElem.tagName().toLower().contains("meta")){
        qDebug() << rootElem.firstChildElement().tagName();
        //  In that case we get the next element
        url = rootElem.firstChildElement().attribute("src");
    }else{
        url = rootElem.attribute("src");
    }

    return url;
}

void UBApplication::loadUrl(const QString &url)
{
    if (webController)
        webController->loadUrl(url);
}

bool UBApplication::isFromWeb(QString url)
{
    bool res = true;

    if( url.startsWith("uniboardTool://") ||
        url.startsWith("file://") ||
        url.startsWith("/")){
        res = false;
    }

    return res;
}


//bool UBApplication::notify ( QObject * receiver, QEvent * event )
//{
//    qDebug() << event->type();
//}

